import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import LenisScrollProvider from "@/lib/providers/LenisScrollProvider";
import ThemeProvider from "@/lib/providers/ThemeProvider";
import Navbar from "@/components/navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ClerkProvider>
          <LenisScrollProvider />
          <NextTopLoader />
          <ThemeProvider>
            <Navbar />
            <main className="mt-14">{children}</main>
            <Toaster position="top-center" />
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
